version: '3.8'

services:
  app:
    image: api_gateway:v2
    container_name: api-gateway
    build:
      context: ./
      cache_from:
        - my-base-image:nx-base
      dockerfile: ./apps/superflights/Dockerfile
      args:
        NODE_ENV: "development"
        BUILD_FLAG: ""
    env_file: ./apps/superflights/.env.development
    ports:
      - 3000:3000
    depends_on:
      - mongodb
      - rabbitmq
    restart: always
    networks:
      - ms_nestjs

  microservice-flights:
    image: microservice-flights:v2
    container_name: microservice-flights
    build:
      context: ./
      cache_from:
        - my-base-image:nx-base
      dockerfile: ./apps/flights/Dockerfile
      args:
        NODE_ENV: "production"
        BUILD_FLAG: "prod"
    env_file: ./apps/flights/.env.production
    depends_on:
      - mongodb
      - rabbitmq
    restart: always
    networks:
      - ms_nestjs

  microservice-passengers:
    image: microservice-passengers:v2
    container_name: microservice-passengers
    build:
      context: ./
      cache_from:
      - my-base-image:nx-base
      dockerfile: ./apps/passengers/Dockerfile
      args:
        NODE_ENV: "development"
        BUILD_FLAG: ""
    env_file: ./apps/passengers/.env.development
    depends_on:
      - mongodb
      - rabbitmq
    restart: always
    networks:
      - ms_nestjs

  microservice-users:
    image: microservice-users:v2
    container_name: microservice-users
    build:
      context: ./
      cache_from:
      - my-base-image:nx-base
      dockerfile: ./apps/users/Dockerfile
      args:
        NODE_ENV: "development"
        BUILD_FLAG: ""
    env_file: ./apps/users/.env.development
    depends_on:
      - mongodb
      - rabbitmq
    restart: always
    networks:
      - ms_nestjs

  rabbitmq:
    image: rabbitmq:latest
    container_name: rmq
    ports:
      - 5672
      - 15672
    restart: always
    networks:
      - ms_nestjs

  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_DATE_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - mongodb:/data/db
    expose:
      - 27017
    restart: always
    networks:
      - ms_nestjs

volumes:
  mongodb:

networks:
  ms_nestjs:

      